import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CountryService {

  constructor() { }

  countries = [
    { "name": "Afghanistan", "phoneCode": "+93" },
    { "name": "Afrique du Sud", "phoneCode": "+27" },
    { "name": "Albanie", "phoneCode": "+355" },
    { "name": "Algérie", "phoneCode": "+213" },
    { "name": "Allemagne", "phoneCode": "+49" },
    { "name": "Andorre", "phoneCode": "+376" },
    { "name": "Angola", "phoneCode": "+244" },
    { "name": "Antigua-et-Barbuda", "phoneCode": "+1-268" },
    { "name": "Arabie Saoudite", "phoneCode": "+966" },
    { "name": "Argentine", "phoneCode": "+54" },
    { "name": "Arménie", "phoneCode": "+374" },
    { "name": "Australie", "phoneCode": "+61" },
    { "name": "Autriche", "phoneCode": "+43" },
    { "name": "Azerbaïdjan", "phoneCode": "+994" },
    { "name": "Bahamas", "phoneCode": "+1-242" },
    { "name": "Bahreïn", "phoneCode": "+973" },
    { "name": "Bangladesh", "phoneCode": "+880" },
    { "name": "Barbade", "phoneCode": "+1-246" },
    { "name": "Belgique", "phoneCode": "+32" },
    { "name": "Belize", "phoneCode": "+501" },
    { "name": "Bénin", "phoneCode": "+229" },
    { "name": "Bhoutan", "phoneCode": "+975" },
    { "name": "Biélorussie", "phoneCode": "+375" },
    { "name": "Birmanie", "phoneCode": "+95" },
    { "name": "Bolivie", "phoneCode": "+591" },
    { "name": "Bosnie-Herzégovine", "phoneCode": "+387" },
    { "name": "Botswana", "phoneCode": "+267" },
    { "name": "Brésil", "phoneCode": "+55" },
    { "name": "Brunei", "phoneCode": "+673" },
    { "name": "Bulgarie", "phoneCode": "+359" },
    { "name": "Burkina Faso", "phoneCode": "+226" },
    { "name": "Burundi", "phoneCode": "+257" },
    { "name": "Cabo Verde", "phoneCode": "+238" },
    { "name": "Cambodge", "phoneCode": "+855" },
    { "name": "Cameroun", "phoneCode": "+237" },
    { "name": "Canada", "phoneCode": "+1" },
    { "name": "Chili", "phoneCode": "+56" },
    { "name": "Chine", "phoneCode": "+86" },
    { "name": "Chypre", "phoneCode": "+357" },
    { "name": "Colombie", "phoneCode": "+57" },
    { "name": "Comores", "phoneCode": "+269" },
    { "name": "Congo (République Démocratique)", "phoneCode": "+243" },
    { "name": "Congo (République)", "phoneCode": "+242" },
    { "name": "Corée du Nord", "phoneCode": "+850" },
    { "name": "Corée du Sud", "phoneCode": "+82" },
    { "name": "Costa Rica", "phoneCode": "+506" },
    { "name": "Côte d'Ivoire", "phoneCode": "+225" },
    { "name": "Croatie", "phoneCode": "+385" },
    { "name": "Cuba", "phoneCode": "+53" },
    { "name": "Danemark", "phoneCode": "+45" },
    { "name": "Djibouti", "phoneCode": "+253" },
    { "name": "Dominique", "phoneCode": "+1-767" },
    { "name": "Égypte", "phoneCode": "+20" },
    { "name": "El Salvador", "phoneCode": "+503" },
    { "name": "Émirats Arabes Unis", "phoneCode": "+971" },
    { "name": "Équateur", "phoneCode": "+593" },
    { "name": "Érythrée", "phoneCode": "+291" },
    { "name": "Espagne", "phoneCode": "+34" },
    { "name": "Estonie", "phoneCode": "+372" },
    { "name": "Eswatini", "phoneCode": "+268" },
    { "name": "États-Unis", "phoneCode": "+1" },
    { "name": "Éthiopie", "phoneCode": "+251" },
    { "name": "Fidji", "phoneCode": "+679" },
    { "name": "Finlande", "phoneCode": "+358" },
    { "name": "France", "phoneCode": "+33" },
    { "name": "Gabon", "phoneCode": "+241" },
    { "name": "Gambie", "phoneCode": "+220" },
    { "name": "Géorgie", "phoneCode": "+995" },
    { "name": "Ghana", "phoneCode": "+233" },
    { "name": "Grèce", "phoneCode": "+30" },
    { "name": "Grenade", "phoneCode": "+1-473" },
    { "name": "Guatemala", "phoneCode": "+502" },
    { "name": "Guinée", "phoneCode": "+224" },
    { "name": "Guinée-Bissau", "phoneCode": "+245" },
    { "name": "Guinée équatoriale", "phoneCode": "+240" },
    { "name": "Guyana", "phoneCode": "+592" },
    { "name": "Haïti", "phoneCode": "+509" },
    { "name": "Honduras", "phoneCode": "+504" },
    { "name": "Hongrie", "phoneCode": "+36" },
    { "name": "Inde", "phoneCode": "+91" },
    { "name": "Indonésie", "phoneCode": "+62" },
    { "name": "Irak", "phoneCode": "+964" },
    { "name": "Iran", "phoneCode": "+98" },
    { "name": "Irlande", "phoneCode": "+353" },
    { "name": "Islande", "phoneCode": "+354" },
    { "name": "Israël", "phoneCode": "+972" },
    { "name": "Italie", "phoneCode": "+39" },
    { "name": "Jamaïque", "phoneCode": "+1-876" },
    { "name": "Japon", "phoneCode": "+81" },
    { "name": "Jordanie", "phoneCode": "+962" },
    { "name": "Kazakhstan", "phoneCode": "+7" },
    { "name": "Kenya", "phoneCode": "+254" },
    { "name": "Kirghizistan", "phoneCode": "+996" },
    { "name": "Kiribati", "phoneCode": "+686" },
    { "name": "Koweït", "phoneCode": "+965" },
    { "name": "Laos", "phoneCode": "+856" },
    { "name": "Lesotho", "phoneCode": "+266" },
    { "name": "Lettonie", "phoneCode": "+371" },
    { "name": "Liban", "phoneCode": "+961" },
    { "name": "Libéria", "phoneCode": "+231" },
    { "name": "Libye", "phoneCode": "+218" },
    { "name": "Liechtenstein", "phoneCode": "+423" },
    { "name": "Lituanie", "phoneCode": "+370" },
    { "name": "Luxembourg", "phoneCode": "+352" },
    { "name": "Macédoine du Nord", "phoneCode": "+389" },
    { "name": "Madagascar", "phoneCode": "+261" },
    { "name": "Malaisie", "phoneCode": "+60" },
    { "name": "Malawi", "phoneCode": "+265" },
    { "name": "Maldives", "phoneCode": "+960" },
    { "name": "Mali", "phoneCode": "+223" },
    { "name": "Malte", "phoneCode": "+356" },
    { "name": "Maroc", "phoneCode": "+212" },
    { "name": "Marshall (Îles)", "phoneCode": "+692" },
    { "name": "Maurice", "phoneCode": "+230" },
    { "name": "Mauritanie", "phoneCode": "+222" },
    { "name": "Mexique", "phoneCode": "+52" },
    { "name": "Micronésie", "phoneCode": "+691" },
    { "name": "Moldavie", "phoneCode": "+373" },
    { "name": "Monaco", "phoneCode": "+377" },
    { "name": "Mongolie", "phoneCode": "+976" },
    { "name": "Monténégro", "phoneCode": "+382" },
    { "name": "Mozambique", "phoneCode": "+258" },
    { "name": "Namibie", "phoneCode": "+264" },
    { "name": "Nauru", "phoneCode": "+674" },
    { "name": "Népal", "phoneCode": "+977" },
    { "name": "Nicaragua", "phoneCode": "+505" },
    { "name": "Niger", "phoneCode": "+227" },
    { "name": "Nigeria", "phoneCode": "+234" },
    { "name": "Norvège", "phoneCode": "+47" },
    { "name": "Nouvelle-Zélande", "phoneCode": "+64" },
    { "name": "Oman", "phoneCode": "+968" },
    { "name": "Ouganda", "phoneCode": "+256" },
    { "name": "Ouzbékistan", "phoneCode": "+998" },
    { "name": "Pakistan", "phoneCode": "+92" },
    { "name": "Palaos", "phoneCode": "+680" },
    { "name": "Palestine", "phoneCode": "+970" },
    { "name": "Panama", "phoneCode": "+507" },
    { "name": "Papouasie-Nouvelle-Guinée", "phoneCode": "+675" },
    { "name": "Paraguay", "phoneCode": "+595" },
    { "name": "Pays-Bas", "phoneCode": "+31" },
    { "name": "Pérou", "phoneCode": "+51" },
    { "name": "Philippines", "phoneCode": "+63" },
    { "name": "Pologne", "phoneCode": "+48" },
    { "name": "Portugal", "phoneCode": "+351" },
    { "name": "Qatar", "phoneCode": "+974" },
    { "name": "Roumanie", "phoneCode": "+40" },
    { "name": "Royaume-Uni", "phoneCode": "+44" },
    { "name": "Russie", "phoneCode": "+7" },
    { "name": "Rwanda", "phoneCode": "+250" },
    { "name": "Saint-Kitts-et-Nevis", "phoneCode": "+1-869" },
    { "name": "Saint-Vincent-et-les-Grenadines", "phoneCode": "+1-784" },
    { "name": "Sainte-Lucie", "phoneCode": "+1-758" },
    { "name": "Saint-Marin", "phoneCode": "+378" },
    { "name": "Salomon (Îles)", "phoneCode": "+677" },
    { "name": "Salvador", "phoneCode": "+503" },
    { "name": "Samoa", "phoneCode": "+685" },
    { "name": "São Tomé-et-Principe", "phoneCode": "+239" },
    { "name": "Sénégal", "phoneCode": "+221" },
    { "name": "Serbie", "phoneCode": "+381" },
    { "name": "Seychelles", "phoneCode": "+248" },
    { "name": "Sierra Leone", "phoneCode": "+232" },
    { "name": "Singapour", "phoneCode": "+65" },
    { "name": "Slovaquie", "phoneCode": "+421" },
    { "name": "Slovénie", "phoneCode": "+386" },
    { "name": "Somalie", "phoneCode": "+252" },
    { "name": "Soudan", "phoneCode": "+249" },
    { "name": "Soudan du Sud", "phoneCode": "+211" },
    { "name": "Sri Lanka", "phoneCode": "+94" },
    { "name": "Suède", "phoneCode": "+46" },
    { "name": "Suisse", "phoneCode": "+41" },
    { "name": "Suriname", "phoneCode": "+597" },
    { "name": "Syrie", "phoneCode": "+963" },
    { "name": "Tadjikistan", "phoneCode": "+992" },
    { "name": "Tanzanie", "phoneCode": "+255" },
    { "name": "Tchad", "phoneCode": "+235" },
    { "name": "Tchéquie", "phoneCode": "+420" },
    { "name": "Thaïlande", "phoneCode": "+66" },
    { "name": "Timor oriental", "phoneCode": "+670" },
    { "name": "Togo", "phoneCode": "+228" },
    { "name": "Tonga", "phoneCode": "+676" },
    { "name": "Trinité-et-Tobago", "phoneCode": "+1-868" },
    { "name": "Tunisie", "phoneCode": "+216" },
    { "name": "Turkménistan", "phoneCode": "+993" },
    { "name": "Turquie", "phoneCode": "+90" },
    { "name": "Tuvalu", "phoneCode": "+688" },
    { "name": "Ukraine", "phoneCode": "+380" },
    { "name": "Uruguay", "phoneCode": "+598" },
    { "name": "Vanuatu", "phoneCode": "+678" },
    { "name": "Vatican", "phoneCode": "+379" },
    { "name": "Venezuela", "phoneCode": "+58" },
    { "name": "Viêt Nam", "phoneCode": "+84" },
    { "name": "Yémen", "phoneCode": "+967" },
    { "name": "Zambie", "phoneCode": "+260" },
    { "name": "Zimbabwe", "phoneCode": "+263" }
  ]
}